a = input('Digite algo: ')
print('A possibilidade da palavra {} ser composta por numeros é {}'.format(a, a.isnumeric()))
print('A possibilidade da palavra {} ser composta por letras é {}'.format(a, a.isalpha()))
print('A possibilidade da palavra {} ser composta por letras e numeros é {}'.format(a, a.isalnum()))
print('A possibilidade da palavra {} ser composta só por espaços é {}'.format(a, a.isspace()))
print('A possibilidade da palavra {} ser composta só por letras maiusculas é {}'.format(a, a.isupper()))
print('A possibilidade da palavra {} ser composta só por letras minusculas é {}'.format(a, a.islower()))
print('A possibilidade da palavra {} ser composta por letras maiusculas e minusculas é {}'.format(a, a.istitle()))
print('Parabens, a palavra chave : {} foi totalmente analisada'.format(a))
